# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.32
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 17.0
org_name: PT. Arkana Solusi Digital
org_slug: nrkholid
rebel_module_groups: []
repo_description: Training Technical Odoo V17
repo_name: Training Technical Odoo V17
repo_slug: practice-odoo-v17
repo_website: https://github.com/nrkholid/practice-odoo-v17
use_pyproject_toml: true
use_ruff: true

